import React from 'react';

import { BrowserRouter } from 'react-router-dom';

import PersonList from './personList';

export default {
  component: PersonList,
  title: 'personList',
};

const Template = (args) => (
  <BrowserRouter>
    <PersonList {...args} />
  </BrowserRouter>
);

export const Default = Template.bind({});
Default.args = {
  persons: [
    {
      adult: false,
      gender: 1,
      id: 15555,
      known_for: [
        {
          adult: false,
          backdrop_path: '/mfJepkInUbiZ0mFXFhDNz8ko6Zr.jpg',
          genre_ids: [18, 9648, 878],
          id: 1124,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'The Prestige',
          overview:
            '로버트 앤지어는 상류층 집안에서 자란 쇼맨십이 강한 마술사. 반면 고아로 사람들과 잘 어울리지 못하는 알프레드 보든은 아이디어를 남들에게 보여 줄 배짱은 없지만 누구보다도 뛰어난 재능을 가진 천재이다. 두 사람은 서로를 아끼는 친구이자 선의의 경쟁자. 그러나 그들이 최고라 자부했던 수중 마술이 실패로 돌아가면서 두 사람은 철천지 원수로 돌변한다. 상대방 마술의 비밀을 캐내려 경쟁을 벌이는 가운데, 로버트는 알프레드의 비밀을 알아내기 위해 자신의 조수이자 사랑하는 여인 올리비아를 알프레드에게 접근하게 만든다.',
          poster_path: '/rwEc7SgXu7b5Yo8Co4CvSinF91v.jpg',
          release_date: '2006-10-19',
          title: '프레스티지',
          video: false,
          vote_average: 8.2,
          vote_count: 12413,
        },
        {
          adult: false,
          backdrop_path: '/4bAwGmE9Sl4FeXoHWVWLXkURHbe.jpg',
          genre_ids: [28, 53, 878],
          id: 59967,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Looper',
          overview:
            '암흑의 도시로 변해버린 2074년 캔자스. 시간여행은 불법으로 규정돼 거대 범죄 조직들 사이에서 비밀리에 이용된다. 완벽한 증거 소멸과 시체 처리를 위해 미래의 조직들은 제거 대상들을 비밀리에 2044년에 활동하고 있는 루퍼라는 킬러들에게 보낸다. 어느 날 시궁창 같은 도시에서 완벽한 임무수행으로 최고의 자리를 지켜내고 있는 킬러 조(조셉 고든 레빗)의 앞에 새로운 타겟이 등장한다. 그는 바로 레인메이커에 의해 살해 당한 아내를 다시 살려내고자 과거로 돌아온 30년 후의 바로 자신(브루스 윌리스)임을 알게 되는데...',
          poster_path: '/7MPHCBEek4qbsuauUvrVViOgQ5J.jpg',
          release_date: '2012-09-26',
          title: '루퍼',
          video: false,
          vote_average: 6.8,
          vote_count: 8589,
        },
        {
          backdrop_path: '/hiK4qc0tZijQ9KNUnBIS1k4tdMJ.jpg',
          first_air_date: '2004-11-16',
          genre_ids: [18, 35, 9648],
          id: 1408,
          media_type: 'tv',
          name: '하우스',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'House',
          overview:
            '2004년 11월 FOX에서 방영을 시작한 미스터리 의학 시리즈. 프린스턴 플레인즈보로 대학병원의 진단의학과 과장인 그레고리 하우스는 환자들을 성심성의껏 돌보는 데는 영 꽝인 의사. 사사건건 병원 원장인 리사 커디와 부딪히는 그는 못된 매너와 그 매너를 더욱 돋보이게 하는 외모로 유명하지만, 또한 창조적인 생각과 결점없는 의학적 본능을 유감없이 발휘하는 최고의 의사이기도 하다. 천재적인 분석능력을 갖춘 전염병 전문의로서 그가 이제 인명을 살리기 위한 흥미롭고 미스터리한 의학의 퍼즐을 풀어간다.',
          poster_path: '/lkvhReTBZ2Ksl0Dl5Oplsf6UYkF.jpg',
          vote_average: 8.6,
          vote_count: 4206,
        },
      ],
      known_for_department: 'Acting',
      name: 'Piper Perabo',
      popularity: 186.806,
      profile_path: '/aP9QqLm4JZxLwp2CiUbEh5zrpVI.jpg',
    },
    {
      adult: false,
      gender: 0,
      id: 1333809,
      known_for: [
        {
          adult: false,
          backdrop_path: '/eZdjRtPKPd4XLWy5aUovh4QVL5u.jpg',
          genre_ids: [37, 28],
          id: 11969,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Tombstone',
          overview:
            '남북 전쟁 뒤의 서부는 새로운 삶을 꿈꾸며 모여드는 사람들로 인해 어수선하고 혼란스럽다. 전설적인 보안관 와이어트는 은퇴 후 흩어져 있던 두 형 버질, 모건과 함께 툼스톤에 정착한다. 그들은 새로운 사업을 하며 돈을 벌고자 하는 데 극심하게 혼란한 툼스톤 거리를 외면하지 못한 형 버질은 보안관직을 맡고 거리에서 총을 들고 다니지 못하게 한다. 이로 인해 그곳에서 이권을 갖고 있던 악당 링고 패거리와의 사이에 긴장감이 감돈다. 치과 의사에서 노름꾼으로 전락한 닥 할리데이는 와이어트와 각별한 사이인데 자신의 지병인 결핵을 치료하고자 툼스톤으로 오게 되고 와이어트 형제와 행동을 함께 한다. 그러던 어느 날 링고 패거리들이 와이어트 형제들을 습격한다는 소문이 돌고 드디어 OK목장에서 역사적인 결투가 벌어지게 되는데...',
          poster_path: '/wu1VoC8qPJ89jaZM394xt8G3s1Y.jpg',
          release_date: '1993-12-25',
          title: '툼스톤',
          video: false,
          vote_average: 7.6,
          vote_count: 1454,
        },
        {
          backdrop_path: '/5YTM1bh3Jyfy9IP2eS64W3JDeGs.jpg',
          first_air_date: '2018-06-20',
          genre_ids: [37, 18],
          id: 73586,
          media_type: 'tv',
          name: '옐로우스톤',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Yellowstone',
          overview:
            '미국 최초의 국립 공원과 국경을 접하는 사람들의 지속적인 공격을 받으면서 미국에서 가장 큰 목장을 관리하는 존 던트의 이야기',
          poster_path: '/43nVQqVsrshaOx9GfJq6JstsfCX.jpg',
          vote_average: 8,
          vote_count: 673,
        },
        {
          adult: false,
          backdrop_path: '/xbxqoukQb2lRht4gozESZw4UFlG.jpg',
          genre_ids: [28, 35],
          id: 398177,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Just Getting Started',
          overview:
            '호화 실버 리조트 빌라 카프리의 잘나가는 매니저 다이버(모건 프리먼)는 과거 범죄 조직의 리더들을 변호했던 변호사 출신이다. 어느 날 빌라 카프리에 전직 군 출신의 매력남 레오(토미 리 존스)가 들어오면서 최고의 남자 자리를 놓고 경쟁이 벌어진다. 하지만 다이버를 노리는 암살자의 출현에 두 사람은 힘을 합치기로 하는데.',
          poster_path: '/70eVsU4nvVidEs7mpPcEcBlIpmx.jpg',
          release_date: '2017-12-01',
          title: '저스트 게팅 스타티드',
          video: false,
          vote_average: 4.9,
          vote_count: 172,
        },
      ],
      known_for_department: 'Acting',
      name: 'Forrie J. Smith',
      popularity: 112.116,
      profile_path: '/A3JvvFVzfF5M7Pvi2csISkoqxDC.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 12852,
      known_for: [
        {
          adult: false,
          backdrop_path: '/fCCvn3xsG29TGKJPvZgTRppsDgk.jpg',
          genre_ids: [80, 18, 53],
          id: 6977,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'No Country for Old Men',
          overview:
            '사막 한 가운데서 사냥을 즐기던 모스는 총격전이 벌어진 듯 출혈이 낭자한 사건 현장을 발견한다. 모스는 물 한 모금을 갈구하는 단 한명의 생존자를 외면한 채 떠나다가 우연히 200만 달러가 들어있는 가방을 발견한다. 횡재를 했지만 물을 달라는 요구를 거절한 게 내심 꺼림칙했던 모스는 새벽녘에 현장을 다시 방문하게 되고, 때마침 마주친 경찰에게 쫓기는 신세가 되고 만다. 여기에 200만 달러가 든 가방을 찾는 살인마 안톤 시거와 보안관 벨이 끼어들면서 이야기는 혼돈과 폭력의 결말로 치달아 간다.',
          poster_path: '/2SU078qZf8ZTNfl6XlqgYiQohhG.jpg',
          release_date: '2007-11-08',
          title: '노인을 위한 나라는 없다',
          video: false,
          vote_average: 7.9,
          vote_count: 9185,
        },
        {
          backdrop_path: '/hPea3Qy5Gd6z4kJLUruBbwAH8Rm.jpg',
          first_air_date: '2015-02-08',
          genre_ids: [35, 80, 18],
          id: 60059,
          media_type: 'tv',
          name: '베터 콜 사울',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Better Call Saul',
          overview:
            '브레이킹 배드의 스핀오프. 베터 콜 사울 (Better call Saul) 이라는 제목은 브레이킹 배드에서 등장하는 사울 굿맨의 변호사 광고 슬로건에서 따왔다. 2002년을 배경으로 삼류 변호사 지미 맥길이 악덕 변호사 사울 굿맨으로 변하게 되는 과정을 그린다.',
          poster_path: '/cU0kAjGjA6d2XjBzJMUIEVKiGDb.jpg',
          vote_average: 8.4,
          vote_count: 2431,
        },
        {
          backdrop_path: '/x4lxFIhhrDI4nWtV8osnYwbGESV.jpg',
          first_air_date: '2009-09-23',
          genre_ids: [35],
          id: 1421,
          media_type: 'tv',
          name: '모던 패밀리',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Modern Family',
          overview:
            '에미상을 받은 이 시트콤은 로스앤젤레스에 사는 제이 프리쳇과 각양각색의 가족이 일상에서 수많은 난관을 만나고 해결해 나가는 이야기를 그린다.',
          poster_path: '/fCiOen2bpru5JhzlaNkaNWNd9eP.jpg',
          vote_average: 7.7,
          vote_count: 1573,
        },
      ],
      known_for_department: 'Acting',
      name: 'Barry Corbin',
      popularity: 86.273,
      profile_path: '/avNg0rmudSPg30f8Xt9BwkPDC17.jpg',
    },
    {
      adult: false,
      gender: 1,
      id: 67837,
      known_for: [
        {
          adult: false,
          backdrop_path: '/u0jVmyqnMmvFuTWRaUuPdRrIZQP.jpg',
          genre_ids: [18, 35, 10749],
          id: 82693,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Silver Linings Playbook',
          overview:
            '아내의 외도를 목격하고 한 순간 감정이 폭발해 아내, 직장, 집은 물론, 정신까지 잃게 된 이 남자.  8개월의 병원 생활 후 ‘긍정의 힘’을 믿으며 아내와 자신의 인생을 되찾기 위해 고군분투 노력중!  긍정의 주문을 외우며 마인드 컨트롤을 해보지만, 감정은 통제불능이요 ~아내에게는 접근명령 상태라~  내숭 없는 이. 여. 자. 정말 대책 없다?!  연애세포 과다 방출, 치유확률 -100%  남편의 죽음 이후 외로움 때문에 회사 내 모든 직원들과 관계를 맺은 티파니. 저돌적인 대시와 내숭 없는 애정 표현으로 티파니는 팻의 인생에 갑자기 뛰어든다. 그의 조깅코스에 불쑥 나타나는가 하면 함께 자자는 말을 거침없이 쏟아내며 예측불허의 행동으로 팻을 당황스럽게 만드는 그녀, 그런 티파니가 팻은 부담스럽기만 하다.  재생률 100%! 연애세포 복구프로젝트가 시작된다  쉽게 자신에게 넘어오지 않는 ‘팻’을 위해 티파니는 ‘헤어진 아내와의 재결합을 도와주는 대신, 자신과 함께 댄스 대회에 참가’하자는 달콤한 제안을 하는데…  과연 그들은 사랑 때문에 고장(?) 난 러브멘탈을 복구하고 그들만의 ‘실버라이닝’을 찾을 수 있을까?',
          poster_path: '/5LJbCTGuS2Elo5L50yYhCLlWNIE.jpg',
          release_date: '2012-09-08',
          title: '실버라이닝 플레이북',
          video: false,
          vote_average: 7.1,
          vote_count: 10151,
        },
        {
          adult: false,
          backdrop_path: '/pDKFL1zcHzEpmz4MJA5JJnRbJeD.jpg',
          genre_ids: [53, 18, 878],
          id: 405774,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Bird Box',
          overview:
            '미지의 재앙이 인류를 휩쓴다. 세상이 뒤집힌 지 5년. 용케 살아남은 여자와 그녀의 아이들이 또다시 위기에 처한다. 안전한 곳을 향해, 그들은 필사적인 모험을 감행한다.',
          poster_path: '/dB7jNL5I3hb7b1zsGD5OEoSl2BQ.jpg',
          release_date: '2018-12-13',
          title: '버드 박스',
          video: false,
          vote_average: 6.9,
          vote_count: 7986,
        },
        {
          adult: false,
          backdrop_path: '/bAI7aPHQcvSZXvt7L11kMJdS0Gm.jpg',
          genre_ids: [35, 18],
          id: 371638,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'The Disaster Artist',
          overview:
            '헐리우드 유명 배우를 꿈꾸지만 소심한 성격으로 무대 위해서 준비한 걸 뽐내지 못하는 배우 지망생 그렉 세스테로 앞에 자신감이 넘치는 배우 지망생 토미 웨소가 나타난다.  같은 꿈을 가지고 급격히 친해진 그렉과 토미는 대스타가 되길 꿈꾸며 LA 로 떠나지만, 끼도 재능도 없고 열정만 있는 두 배우에겐 좀처럼 기회가 주어지지 않는다.  캐스팅 근처에도 못 가는 토미는 불현듯 더 이상 캐스팅을 기다리지 않고 자신의 영화를 만들겠다고 선언하고, 시나리오 집필부터, 감독, 연기, 600만불에 육박하는 제작비 조달까지 1인 다역을 하며 영화를 완성해낸다.',
          poster_path: '/jj84nF5vYRD0HUTowBKcrKk8hZP.jpg',
          release_date: '2017-03-12',
          title: '더 디제스터 아티스트',
          video: false,
          vote_average: 7.1,
          vote_count: 2929,
        },
      ],
      known_for_department: 'Acting',
      name: 'Jacki Weaver',
      popularity: 83.677,
      profile_path: '/1bc9fUnbFQdDeXKho22eyXrNR63.jpg',
    },
    {
      adult: false,
      gender: 1,
      id: 17521,
      known_for: [
        {
          adult: false,
          backdrop_path: '/oLmifRdaETboot2PXxpZN8NqHhK.jpg',
          genre_ids: [28, 12, 80, 9648],
          id: 10528,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Sherlock Holmes',
          overview:
            'CHAPTER1. 세기의 명탐정_“범죄는 흔하다. 그러나 논리는 흔치 않다” 셜록 홈즈(로버트 다우니 주니어), 천재적인 추리 능력과 주먹의 힘까지 갖추고 친구 왓슨 박사(주드 로)와 함께 치밀하게 얽힌 미스터리 속에서 진실을 찾아내는 명탐정. 그에게 이제껏 경험하지 못했던 최대의 위협이자 지금껏 그토록 갈구했던 진정한 모험이 몰려오고 있었다.  CHAPTER2. 예고된 살인_“홈즈, 당신과 나는 자연 법칙을 뒤집어 놓을 여정에 올랐소”다섯 명의 여인들이 종교 의식의 제물로 끔찍하게 살해되는 사건이 잇따라 발생하고, 홈즈와 왓슨은 간발의 차이로 마지막 희생자가 될뻔한 여인을 구한다. 범인은 비밀 종교집단 소속의 블랙우드(마크 스트롱). 붙잡힌 블랙우드는 사형 집행일이 다가올수록 강력한 어둠의 힘을 발휘하고, 자신의 죽음은 계획의 일부에 지나지 않는다며 홈즈에게 경고한다.  CHAPTER3. 죽은 자의 부활_“증거 없는 이론은 위험하네. 사실을 이론에 맞추려 들테니” 블랙우드의 경고는 현실로 나타나고, 죽었던 그의 부활은 도시 전체를 공포 속에 몰아넣는다. 그러나 이것은 홈즈에게는 게임의 시작일 뿐. 블랙우드의 치명적인 음모를 저지하기 위해 홈즈와 왓슨은 고대의 신비한 주술과 현대의 경이로운 신기술이 혼재한 세계로 뛰어든다.  CHAPTER4. 진정한 목적_“가장 사소한 단서가 가장 중요한 증거가 되는 법이지”그러나 홈즈가 해결해야 할 것은 사건만이 아니었다. 그의 앞에 헤어진 연인 아이린(레이철 맥아담스)이 등장해 적인지 아닌지 모호한 행동으로 그를 더욱 혼란에 빠뜨린다.  한편, 최강의 콤비 플레이로 사건을 파헤치던 홈즈와 왓슨은 단서들이 공통의 연결고리로 어떤 징후를 나타낸다는 것을 발견하고, 이것이 세상을 파멸시킬 거대한 음모였음을 알게 되는데… 정확한 논리를 무기로, 일격의 주먹을 방어막으로, 세상을 구할 홈즈의 추리가 시작된다!',
          poster_path: '/57lDlyrA7tWDyscroixKSJRerFU.jpg',
          release_date: '2009-01-01',
          title: '셜록 홈즈',
          video: false,
          vote_average: 7.2,
          vote_count: 11815,
        },
        {
          adult: false,
          backdrop_path: '/nVMalJRUsOeGP5xPx9ULmirZ4cJ.jpg',
          genre_ids: [12, 28, 80, 9648],
          id: 58574,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Sherlock Holmes: A Game of Shadows',
          overview:
            '더욱 강렬하게, 더욱 스릴 있게 세상을 구할 홈즈의 추리가 다시 시작된다!  왓슨과 더 많은 시간을 보내기 위해 왓슨의 부인과 경쟁하는 홈즈 앞에 또 한 번 세상에서 가장 명석한 두뇌를 증명할 과제가 주어진다! 셜록 홈즈는 유럽에서 발생하는 연쇄 폭탄 테러사건, 강대국들의 전쟁 위기고조, 미국 철강 왕의 죽음 등 전세계에서 벌어지는 풀리지 않는 사건들이 모두 연결되어 있고 그 배후에 평생의 숙적 모리아티 교수(자레드 해리스)의 더 큰 음모가 숨겨져 있음을 직감한다.  조사 과정에서 만나게 된 집시이자 점술가인 묘령의 프랑스 여인 심(노미 파라스)을 통해 살인사건에 대해 정보를 얻지만 이를 계기로 여인은 킬러의 다음 목표물이 된다. 이에 홈즈는 그녀의 목숨을 구하기 위해, 그녀는 죽음을 피하기 위해 홈즈에게 협조하고 대륙을 넘나드는 험난한 모험 앞에서 교활한 모리아티 교수는 항상 한 발 먼저 죽음의 덫을 놓고 기다린다.  모리아티 교수의 계획이 성공하게 되면 역사가 뒤바뀔 정도로 세상은 위험해진다.  거대한 음모에 맞선 홈즈의 활약이 다시 펼쳐진다!',
          poster_path: '/vD1HZvrPW9FoYQFGr0ADTCsNFau.jpg',
          release_date: '2011-11-22',
          title: '셜록 홈즈: 그림자 게임',
          video: false,
          vote_average: 7.1,
          vote_count: 8642,
        },
        {
          adult: false,
          backdrop_path: '/yBq4jWZLaEJIssuVx2fAysEwJnt.jpg',
          genre_ids: [18, 10749],
          id: 4348,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Pride & Prejudice',
          overview:
            '베넷 가의 다섯 자매 중 둘째인 엘리자베스는 사랑하는 사람과의 결혼을 믿는 자존심 강하고 영리한 소녀이다. 부유하고 명망있는 가문의 신사 빙리와 그의 친구 다아시가 여름 동안 대저택에 머물게 되고, 댄스 파티에서 처음 만난 엘리자베스와 다아시는 서로에게서 눈을 떼지 못한다. 다아시는 아름답고 지적인 그녀의 매력에 점점 빠져들고, 폭우가 쏟아지는 날 비바람이 몰아치는 언덕에서 가슴 속 깊은 곳에 담아둔 뜨거운 사랑을 그녀에게 고백한다. 하지만 다아시가 빙리와 제인의 결혼을 제인이 명망있는 가문 출신이 아니라는 이유로 반대한 것을 알게 되자, 그를 오만하고 편견에 가득 찬 속물로 여기며 외면하는데...',
          poster_path: '/tQ303fQUo5Mv5Txgpl2DPS2Jq0e.jpg',
          release_date: '2005-09-16',
          title: '오만과 편견',
          video: false,
          vote_average: 8.1,
          vote_count: 6152,
        },
      ],
      known_for_department: 'Acting',
      name: 'Kelly Reilly',
      popularity: 82.037,
      profile_path: '/l8aQsryOQvxgX6SdZ4XtzU8KEXn.jpg',
    },
    {
      adult: false,
      gender: 1,
      id: 1230687,
      known_for: [
        {
          backdrop_path: '/hiK4qc0tZijQ9KNUnBIS1k4tdMJ.jpg',
          first_air_date: '2004-11-16',
          genre_ids: [18, 35, 9648],
          id: 1408,
          media_type: 'tv',
          name: '하우스',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'House',
          overview:
            '2004년 11월 FOX에서 방영을 시작한 미스터리 의학 시리즈. 프린스턴 플레인즈보로 대학병원의 진단의학과 과장인 그레고리 하우스는 환자들을 성심성의껏 돌보는 데는 영 꽝인 의사. 사사건건 병원 원장인 리사 커디와 부딪히는 그는 못된 매너와 그 매너를 더욱 돋보이게 하는 외모로 유명하지만, 또한 창조적인 생각과 결점없는 의학적 본능을 유감없이 발휘하는 최고의 의사이기도 하다. 천재적인 분석능력을 갖춘 전염병 전문의로서 그가 이제 인명을 살리기 위한 흥미롭고 미스터리한 의학의 퍼즐을 풀어간다.',
          poster_path: '/lkvhReTBZ2Ksl0Dl5Oplsf6UYkF.jpg',
          vote_average: 8.6,
          vote_count: 4203,
        },
        {
          backdrop_path: '/vxrpEBnnwUPDDJ0cSKi0Pi9zdlS.jpg',
          first_air_date: '2013-01-11',
          genre_ids: [80, 18],
          id: 41727,
          media_type: 'tv',
          name: '밴쉬',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Banshee',
          overview:
            "교도소에서 10년을 복역 하고 출소한 한 남자가 옛 여자친구를 찾아 펜실베니아주의 작은 마을 '밴쉬'를 찾아오게 된다. 남자는 마을 외곽 술집에서 벌어진 싸움에 휘말리는데 여기서 죽은 남자가 밴쉬에 새로 부임 하려던 보안관 루카스 후드라는 것을 알게 된다. 그는 예전부터 곧잘 함께 일하고 여자친구가 밴쉬에 있다는 것도 알려줬던 동료 죠브에게 부탁하여 죽은 보안관의 신분으로 위장 한 뒤 순식간에 범죄자에서 경찰로 탈바뀜 한다. 그리고 밴쉬의 경제를 사실상 지배하고 있는 악랄한 사업가 프록터와 자신의 전 여자친구 였던 아나스타샤등 수많은 사람들과 엮이며 여러가지 사건에 휘말리게 되는데....  과격한 성적 묘사, 퀄리티 높은 액션과 폭력성으로 인기를 끌었으며 2016년 시즌 4를 끝으로 종영하였다.",
          poster_path: '/5nXFiz8Rn8eezVjSTZBd7HmnF1G.jpg',
          vote_average: 7.9,
          vote_count: 759,
        },
        {
          backdrop_path: '/6slPhy6cI8SxH9VgqyAErldJGxx.jpg',
          first_air_date: '2015-11-17',
          genre_ids: [18],
          id: 62650,
          media_type: 'tv',
          name: '시카고 메드',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Chicago Med',
          overview:
            '대도시 시카고에 위치한 병원을 배경으로, 매일 반복되는 아수라장 속에서 다양한 사건 사고와 마주하며 함께 난관을 헤쳐나가는 의료진들의 이야기를 그리는 메디컬 드라마',
          poster_path: '/8sWkBKCZ4FrzllsLjMQpiFxZWwM.jpg',
          vote_average: 8.4,
          vote_count: 756,
        },
      ],
      known_for_department: 'Acting',
      name: 'Jennifer Landon',
      popularity: 72.204,
      profile_path: '/o1XDkIoyZTwjSXF9SE7mTZb8Xeb.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 1215399,
      known_for: [
        {
          adult: false,
          backdrop_path: '/4NdAMnBwSAaSsUjoXkcU5aW28RF.jpg',
          genre_ids: [28, 80, 53],
          id: 273481,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Sicario',
          overview:
            '미국과 멕시코의 국경지역 후아레즈는 멕시코 최대 마약조직의 본거지이자 온갖 범죄의 온상지. FBI 요원 케이트는 어린이 납치사건을 수사하다가 멕시코 마약조직의 정체를 알게 되고 CIA가 계획하는 마약조직 소탕작전에 자원한다. 그곳에서 소탕작전을 이끄는 책임자 맷과 멕시코 검사 출신의 알레한드로를 만난다. 작전이 전개되면서 수사는 법의 테두리를 넘지 말아야 한다는 케이트의 정의와 원칙은 수단과 방법을 가리지 않고 임무를 완수하려는 맷과 개인적인 복수를 위해 작전에 개입한 알레한드로 때문에 흔들린다.',
          poster_path: '/oVA4Rx01OUAYdLOiBNBPjaG7I7v.jpg',
          release_date: '2015-09-17',
          title: '시카리오:  암살자의 도시',
          video: false,
          vote_average: 7.4,
          vote_count: 6556,
        },
        {
          adult: false,
          backdrop_path: '/kQGxGXzYiCumY8kmXXpgbZyZQK8.jpg',
          genre_ids: [80, 18, 9648, 53],
          id: 395834,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Wind River',
          overview:
            '보름달이 뜬 어느 날 밤, 발자국마저 사라지는 고요한 설원 위를 맨발로 달리던 한 소녀가 피를 토하며 죽는다. 안간힘을 쓰며 뛰어가던 그녀가 결국 피를 토하며 쓰러져 죽어 있는 모습을 사냥꾼 코리(제레미 레너)가 발견한다. 피해자는 그의 친구의 딸. 신입 FBI요원 제인(엘리자베스 올슨)이 사건 담당자로 그곳에 도착하지만 범인이 남긴 증거는 눈보라에 휩싸여 점점 사라지고, 수사는 난항을 겪는다. 3년 전, 윈드 리버에서 벌어진 살인 사건과의 유사점을 발견한 코리가 수사에 공조하면서  두 사람은 범인의 그림자에 빠른 속도로 접근하는데...',
          poster_path: '/lskBfr1zqKcgl6RYukNBt6pRWVj.jpg',
          release_date: '2017-08-03',
          title: '윈드 리버',
          video: false,
          vote_average: 7.4,
          vote_count: 3826,
        },
        {
          adult: false,
          backdrop_path: '/GZx3RAiTJAhXOdhLLyCAbqRl11.jpg',
          genre_ids: [37, 80],
          id: 338766,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Hell or High Water',
          overview:
            '빚더미에 시달리던 두 형제, 토비(크리스 파인)과 태너(벤 포스터).  가족의 유일한 재산이자, 어머니의 유산인 농장의 소유권 마저 은행 차압위기에 놓이게 된다.  절망적인 현실에서 가족을 지키기 위해 연쇄 은행 강도 계획을 꾸미는 형제.  동생을 위해서라면 어떠한 일도 서슴지 않는 전과자 출신의 형 태너와 차분하고 이성적인 성격의 동생 토비는 범죄에 성공한다.  한편, 연달아 발생한 은행강도 사건을 수사하던 베테랑 형사 해밀턴(제프 브리지스)은 치밀한 범죄 수법을 본능적으로 직감하고 수사망을 좁혀 그들을 추격하기 시작하는데.."',
          poster_path: '/5dy5ihLUwXmjxKi1AeLxBRDzjSD.jpg',
          release_date: '2016-08-12',
          title: '로스트 인 더스트',
          video: false,
          vote_average: 7.3,
          vote_count: 3539,
        },
      ],
      known_for_department: 'Writing',
      name: 'Taylor Sheridan',
      popularity: 64.93,
      profile_path: '/vdGTrPJG95AhBXr3xId5Fj8cTCu.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 1136406,
      known_for: [
        {
          adult: false,
          backdrop_path: '/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg',
          genre_ids: [12, 28, 878],
          id: 299536,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Avengers: Infinity War',
          overview:
            '타노스는 6개의 인피니티 스톤을 획득해 신으로 군림하려 한다. 그것은 곧 인류의 절반을 학살해 우주의 균형을 맞추겠다는 뜻. 타노스는 닥터 스트레인지가 소유한 타임 스톤, 비전의 이마에 박혀 있는 마인드 스톤을 차지하기 위해 지구를 침략한다. 아이언맨과 스파이더맨은 가디언즈 오브 갤럭시의 멤버들과 타노스를 상대한다. 지구에선 캡틴 아메리카, 완다, 블랙 위도우, 블랙 팬서 등이 비전을 지키기 위해 뭉친다.',
          poster_path: '/kmP6viwzcEkZeoi1LaVcQemcvZh.jpg',
          release_date: '2018-04-25',
          title: '어벤져스: 인피니티 워',
          video: false,
          vote_average: 8.3,
          vote_count: 23269,
        },
        {
          adult: false,
          backdrop_path: '/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg',
          genre_ids: [12, 878, 28],
          id: 299534,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Avengers: Endgame',
          overview:
            '어벤져스의 패배 이후 지구는 초토화됐고 남은 절반의 사람들은 정신적 고통을 호소하며 하루하루를 근근이 버텨나간다. 와칸다에서 싸우다 생존한 히어로들과 우주의 타이탄 행성에서 싸우다 생존한 히어로들이 뿔뿔이 흩어졌는데, 아이언맨과 네뷸라는 우주를 떠돌고 있고 지구에 남아 있는 어벤져스 멤버들은 닉 퓨리가 마지막에 신호를 보내다 만 송신기만 들여다보며 혹시 모를 우주의 응답을 기다리는 중이다. 애초 히어로의 삶을 잠시 내려놓고 가족과 시간을 보내던 호크아이 역시 헤아릴 수 없는 마음의 상처를 입은 채 사라지고 마는데...',
          poster_path: '/n78LK2t1uQP68Ud0VXHRe0HmKOp.jpg',
          release_date: '2019-04-24',
          title: '어벤져스: 엔드게임',
          video: false,
          vote_average: 8.3,
          vote_count: 19699,
        },
        {
          adult: false,
          backdrop_path: '/7FWlcZq3r6525LWOcvO9kNWurN1.jpg',
          genre_ids: [12, 28, 878],
          id: 271110,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Captain America: Civil War',
          overview:
            '어벤져스가 벌인 전투로 많은 사람들이 불의의 사고를 당하는 등 부수적인 피해가 일어나자 정부는 슈퍼히어로 등록제를 추진하려 한다. 어벤져스의 독자적인 판단에 맡기기보다 직접 관리, 감독하겠다는 게 정부의 속내. 아이언맨은 정부의 방침을 따라야 한다는 입장인 반면, 캡틴 아메리카는 정부의 감시 없이 자유롭게 지구를 지켜야 한다고 주장한다. 어벤져스 내부는 캡틴 아메리카(윈터 솔져, 팔콘, 호크아이, 스칼렛 위치, 앤트맨)와 아이언맨(블랙위도우, 워머신, 블랙 팬서, 비전, 스파이더맨) 두 입장으로 나뉘어 대립하게 되는데...',
          poster_path: '/vaMRzME3Dt73robEjOtDw4SPJGA.jpg',
          release_date: '2016-04-27',
          title: '캡틴 아메리카: 시빌 워',
          video: false,
          vote_average: 7.4,
          vote_count: 18959,
        },
      ],
      known_for_department: 'Acting',
      name: 'Tom Holland',
      popularity: 62.12,
      profile_path: '/2qhIDp44cAqP2clOgt2afQI07X8.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 6614,
      known_for: [
        {
          adult: false,
          backdrop_path: '/bpV8wn48s82au37QyUJ51S7X2Vf.jpg',
          genre_ids: [18],
          id: 489,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Good Will Hunting',
          overview:
            '수학, 법학, 역사학 등 모든 분야에 재능이 있는 윌(맷 데이먼)은 천재적인 두뇌를 가지고 있지만 어린 시절 받은 상처로 인해 세상에 마음을 열지 못하고 절친인 처키(벤 애플렉)와어울려 다니는 불우한 반항아이다. 대학을 청소하면서 벽에서 우연히 접한 수학 문제를 간단히 풀어버린 일을 그 대학 교수 램보가 발견하고 윌에게 관심을 갖지만 윌은 냉대한다. 어느 날 보호관찰 대상인 윌은 폭행죄로 수감되고, 램보 교수는 자신이 감독하겠다는 조건으로 윌을 석방시킨 다음 대학 동기인 심리학 교수 숀(로빈 윌리엄스)에게 그를 부탁한다. 거칠기만 하던 윌은 숀과 함께 시간을 보낼수록 상처를 위로 받으며 조금씩 변화하기 시작하는데...',
          poster_path: '/iHRY9YuBOyga9MHi59pt6KRGXcB.jpg',
          release_date: '1997-12-05',
          title: '굿 윌 헌팅',
          video: false,
          vote_average: 8.1,
          vote_count: 9134,
        },
        {
          adult: false,
          backdrop_path: '/z3ioibdjWZOYeXjoiabFOFOfPI3.jpg',
          genre_ids: [28, 80, 53],
          id: 584,
          media_type: 'movie',
          original_language: 'en',
          original_title: '2 Fast 2 Furious',
          overview:
            '도미니크와의 의리는 지켰지만 경찰로서 자신이 쌓아 왔던 모든 것을 잃은 브라이언은 경찰 뱃지를 반납하고 LA 를 떠나 스트리트 레이서로서 내깃돈을 따며 전국을 떠돌고 있다. 마이애미 연방정부는 돈 세탁을 무역사업으로 둔갑시켜 화려한 사업가 행세를 하고 있는 카터 베론을 검거하려 하지만, 그가 불법 스트리트 레이싱에 관련되었단 사실 이외에는 별 다른 수확을 거두지 못하고 있었다. 이에 마이애미 연방정부는 스트리트 레이서로 그 실력을 인정 받은 브라이언과 전과자인 로만 피어스에게 그를 검거할 수 있는 증거를 찾아 줄 것을 요구하는데...',
          poster_path: '/hdMGwCpmSgHzVw6yEFFTkSQZUFc.jpg',
          release_date: '2003-06-05',
          title: '분노의 질주 2',
          video: false,
          vote_average: 6.4,
          vote_count: 5661,
        },
        {
          adult: false,
          backdrop_path: '/2ZusF7y230mM1NRlg9Ktgrak9Dg.jpg',
          genre_ids: [28, 53],
          id: 117263,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Olympus Has Fallen',
          overview:
            'DMZ에서의 군사적 도발과 계속되는 핵실험으로 인한 세계적인 긴장상황을 완화하고 미사일 위협에 대처하기 위한 한국과 미국의 최고위급회담이 이루어진다. 이때를 기회로 한국측 경호요원으로 신분을 위장한 북한 출신의 ‘강’을 중심으로 한 테러리스트들이 백악관을 초토화시키고 대통령을 인질로 붙잡는다. 그들의 요구조건은 동해에 있는 제7함대 및 DMZ와 한국에 주둔한 미군 28,500명의 철수, 그리고 미국 내 모든 핵미사일을 통제할 수 있는 암호코드!  백악관을 함락시키고 전 세계를 전쟁 위기에 몰아 넣는 테러리스트들!  누군가 그들을 저지해야 한다!',
          poster_path: '/qkBAnvjCAHIsg10cpTeTNWkKYl3.jpg',
          release_date: '2013-03-20',
          title: '백악관 최후의 날',
          video: false,
          vote_average: 6.4,
          vote_count: 5495,
        },
      ],
      known_for_department: 'Acting',
      name: 'Cole Hauser',
      popularity: 54.122,
      profile_path: '/kJyUtNZREd7mes21OrWiCtOugPL.jpg',
    },
    {
      adult: false,
      gender: 1,
      id: 1499908,
      known_for: [
        {
          adult: false,
          backdrop_path: '/l1nYo0yzKjf84atnBDbx0do16vQ.jpg',
          genre_ids: [878, 28, 12, 10751],
          id: 438590,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'A-X-L',
          overview:
            '인공지능 로봇개 액슬을 우연히 발견한 마일스, 미래형 병기로 만들어졌지만 강아지의 특징을 간직한 액슬을 지키기 위해 생사를 건 모험을 시작한다!',
          poster_path: '/laCuF1fFShkWCXlbCuhSEVoWGO1.jpg',
          release_date: '2018-08-23',
          title: '액슬',
          video: false,
          vote_average: 6.3,
          vote_count: 955,
        },
        {
          backdrop_path: '/5YTM1bh3Jyfy9IP2eS64W3JDeGs.jpg',
          first_air_date: '2018-06-20',
          genre_ids: [37, 18],
          id: 73586,
          media_type: 'tv',
          name: '옐로우스톤',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Yellowstone',
          overview:
            '미국 최초의 국립 공원과 국경을 접하는 사람들의 지속적인 공격을 받으면서 미국에서 가장 큰 목장을 관리하는 존 던트의 이야기',
          poster_path: '/43nVQqVsrshaOx9GfJq6JstsfCX.jpg',
          vote_average: 8,
          vote_count: 705,
        },
        {
          adult: false,
          backdrop_path: '/sN1d1WVEhcc7rrstiApJyF7VJnV.jpg',
          genre_ids: [14, 53, 27, 878],
          id: 354251,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Southbound',
          overview:
            '입구는 있어도 출구는 없는 고속도로,  아무리 달려도 끝없는 길에는 오직 잔혹한 공포만이 남는다!  다섯 개의 입구로 들어온 여행자들에게 남겨진 출구는 단 하나, 죽음뿐이다. 과거에서 벗어나기 위해 달려온 두 남자는 출구를 찾을 수 없는 길 위에서 비극적 최후를 맞는다. 공연을 위해 낯선 길을 달리던 여성밴드그룹의 멤버들은 이상하리만치 친절한 이웃을 만나 자신들의 삶을 잃고 새로운 삶을 마주한다. 신호등 하나 없이 암흑만이 쌓인 도로에서 교통사고를 낸 남자는 사고로 생명을 잃어가는 여자를 구하기 위해 고군분투 하지만 노력할수록 그 결과는 참혹하기만 하다. 오랜 시간 잃어버린 여동생을 찾기 위해 노력해 온 남자 앞에 밝혀진 여동생의 진짜 얼굴과 감춰진 가족의 진실은 지옥을 닮아있다. 대학 진학을 앞둔 딸을 데리고 가족휴가를 떠나온 행복한 가족의 여행은 예기치 못한 잔혹한 방문자들로 인해 핏빛으로 붉게 얼룩진다.',
          poster_path: '/uKHDRfkWrAFK7rOMHwxU1C1WOet.jpg',
          release_date: '2015-09-17',
          title: '사우스바운드 – 죽음의 고속도로',
          video: false,
          vote_average: 6,
          vote_count: 459,
        },
      ],
      known_for_department: 'Acting',
      name: 'Hassie Harrison',
      popularity: 51.42,
      profile_path: '/cUu16UFtcmAJwyge5g5sbMstZCc.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 883,
      known_for: [
        {
          adult: false,
          backdrop_path: '/sODk4VuMTt8S56zYFOr1Kx8BFqu.jpg',
          genre_ids: [28, 53, 878, 12],
          id: 95,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Armageddon',
          overview:
            '미국 동부에 운석이 떨어진다. 이는 뉴욕 크기의 소행성이 지구를 향해 돌진하고 있는 증거임을 미국 우주 항공국이 밝힌다. 텍사스 크기의 소행성이 시속 2만 3천 마일의 속도로 지구로 돌진한다는 사실을 알게 되자 나사(미국 항공 우주국)는 대책을 세운다. 남은 시간은 18일. 지구를 구할 유일한 방법은 돌진하는 소행성에 구멍을 뚫어 핵폭탄을 장착, 궤도를 바꾸는 것이다.  지구 최고의 유정 굴착 기술자들이 파견된다. 해리(브루스 윌리스)는 굴착 기술의 전문가로 지구를 구하기 위해 짧은 시간 동안 우주 비행에 대한 교육을 받고 그의 동료들과 소행성으로 떠난다. 프리덤호와 인디펜던스호는 소행성에 접근하지만 인디펜던스호는 유성의 파편을 맞고 추락한다.  해리 일행은 어쩔 수 없이 도착한 인원으로 폭탄 장치를 하기 위해 최선을 다하지만 무선 폭파 장치가 고장나 누군가 그곳에 남아야 하는데...  임무를 무사히 마친 후 지구로 돌아가서 해리의 딸인 그레이스(리브 타일러)와 결혼하기로 한 A.J(벤 애플렉)는 해리와 지구를 구하기 위해 자신이 소행성에 남기로 하나 결정적인 순간 해리는 딸을 위해서 자신이 소행성에 남는데...',
          poster_path: '/8T9xKzzSZij7dxy3ybkingQvoIZ.jpg',
          release_date: '1998-07-01',
          title: '아마겟돈',
          video: false,
          vote_average: 6.8,
          vote_count: 6272,
        },
        {
          adult: false,
          backdrop_path: '/czRXzKy5YcvoVhRUb8RQsFHUDi1.jpg',
          genre_ids: [27, 53],
          id: 424139,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Halloween',
          overview:
            '마이클이 특별 정신병원에 갇히게 된 지 40년이라는 세월이 지났다. 살아남은 로리(제이미 리 커티스)도 이제 할머니가 되었지만, 그날의 악몽을 잊을 수가 없다. 어느 날, 한 다큐멘터리 팀이 마이클을 인터뷰하러 가는데, 이를 계기로 그가 탈출하게 된다. 그리고 40년 전에 죽이지 못한 로리를 찾아 다시 고향마을로 돌아온다.',
          poster_path: '/wnJeyVsUbhnen4hZbYoJdjJHK2c.jpg',
          release_date: '2018-10-18',
          title: '할로윈',
          video: false,
          vote_average: 6.5,
          vote_count: 3624,
        },
        {
          adult: false,
          backdrop_path: '/4GsvnaGqBGA78ccZusXvCH7zzun.jpg',
          genre_ids: [28, 80, 53],
          id: 9679,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Gone in Sixty Seconds',
          overview:
            '한 때, 자동차 절도의 대도로 통하던 멤피스의 동생 킵은 범죄세계에서 손을 씻고 사라진 형의 뒤를 이어 최고급 스포츠카를 훔치는 일을 하고 있다. 롱비치를 거점으로 범죄조직을 지휘하는 칼리트리는 킵에게 50대의 차를 훔쳐오라고 주문한다. 불행하게도 프르쉐를 훔치던 킵은 경찰의 추적을 받게 되고 칼리트리에게 목숨을 잃을 위기에 처하게 되는데...',
          poster_path: '/fDvzisMqmP2M8fcdRJcCPgicXJ7.jpg',
          release_date: '2000-06-09',
          title: '식스티 세컨즈',
          video: false,
          vote_average: 6.4,
          vote_count: 3410,
        },
      ],
      known_for_department: 'Acting',
      name: 'Will Patton',
      popularity: 49.99,
      profile_path: '/2vr8aJacajXz7m4lMc2WdVniCRZ.jpg',
    },
    {
      adult: false,
      gender: 1,
      id: 1042728,
      known_for: [
        {
          backdrop_path: '/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg',
          first_air_date: '2017-05-02',
          genre_ids: [80, 18],
          id: 71446,
          media_type: 'tv',
          name: '종이의 집',
          origin_country: ['ES'],
          original_language: 'es',
          original_name: 'La Casa de Papel',
          overview:
            '1명의 천재, 8명의 공범, 철저히 준비한 세기의 강도. 스페인 조폐국에서 인질극까지 벌인 이들은 과연 포위 경찰을 따돌리고 거액의 돈과 함께 달아날 수 있을까?',
          poster_path: '/e4IK8bunUl8OiYyebFUuRKKHD4m.jpg',
          vote_average: 8.3,
          vote_count: 15435,
        },
        {
          adult: false,
          backdrop_path: '/yEBBtk1eyZltGgJt8Z2zi3KIvvX.jpg',
          genre_ids: [99],
          id: 689249,
          media_type: 'movie',
          original_language: 'es',
          original_title: 'La Casa de Papel: el fenómeno',
          overview:
            "넷플릭스에서 가장 사랑받은 글로벌 콘텐츠로, 세계적 팬덤을 자랑하는 무장 강도들 이야기. 우리는 왜 달리 가면에 열광하며 '벨라, 차오'를 연호하는가. 출연진과 제작진 인터뷰를 통해 그 현상을 분석하고 촬영 비화를 들어본다.",
          poster_path: '/AboUXTrDWEi0PuZUqaft0iwBTm7.jpg',
          release_date: '2020-04-03',
          title: '종이의 집: 신드롬이 된 드라마',
          video: false,
          vote_average: 7.5,
          vote_count: 903,
        },
        {
          adult: false,
          backdrop_path: '/2OFg5p9yarI5zZsUWKCRgBgPctj.jpg',
          genre_ids: [28, 12],
          id: 568620,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Snake Eyes: G.I. Joe Origins',
          overview:
            '상징적인 지.아이.조 영웅인 스네이크 아이즈(헨리 골딩)의 시초를 알아보는 액션으로 무장한 모험 속에서 가만히 앉아 있기 힘들 것이다. 고대 일본의 아라시카게라는 가문의 후계자 스톰 섀도(앤드루 코지)를 구한 뒤 그 가문으로 들어간 스네이크 아이즈는 코브라라는 테러리스트 그룹에 맞서는 전투에 합류한다. 자신의 한계를 밀어붙이는 스네이크 아이즈는 궁극의 전사가 되지만, 과거의 비밀이 수면 위로 드러나자 그의 명예와 충성심이 시험에 들게 된다. 그것이 그가 싸워 온 모든 것을 잃게 된다해도 말이다. 우르술라 코르베로가 배러니스로 출연하며, 서매라 위빙은 스칼릿으로 분한다.',
          poster_path: '/fYH6tztMcuiuvLCuPTudml1JDGT.jpg',
          release_date: '2021-07-22',
          title: '스네이크 아이즈: 지.아이.조',
          video: false,
          vote_average: 6.8,
          vote_count: 868,
        },
      ],
      known_for_department: 'Acting',
      name: 'Úrsula Corberó',
      popularity: 48.156,
      profile_path: '/noNEe22FM78cYuNGH9jwdQ6rdA8.jpg',
    },
    {
      adult: false,
      gender: 1,
      id: 205976,
      known_for: [
        {
          adult: false,
          backdrop_path: '/sLWUtbrpiLp23a0XDSiUiltdFPJ.jpg',
          genre_ids: [28, 12, 14],
          id: 1930,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'The Amazing Spider-Man',
          overview:
            '어릴적 사라진 부모 대신 삼촌 내외와 살고 있는 피터 파커는 평범한 학교 생활을 하며 일상을 보내고, 같은 학교 학생 그웬 스테이시와 첫사랑에 빠져 우정과 사랑, 그리고 둘 만의 비밀을 키워나간다. 어느 날 아버지가 사용했던 가방을 발견하고 부모님의 실종사건에 대한 의심을 품게 된 그는 숨겨져 왔던 과거의 비밀을 추적하게 된다. 아버지의 옛 동료 코너스 박사의 실험실을 찾아가게 된 피터는 우연한 사고로 특별한 능력을 갖게 되고, 피터의 도움으로 연구를 완성한 코너스 박사는 자신의 숨겨진 자아인 악당 리자드를 탄생시키는데...',
          poster_path: '/egsgKNPmMahQgNhmmYxiMVbLPrC.jpg',
          release_date: '2012-06-23',
          title: '어메이징 스파이더맨',
          video: false,
          vote_average: 6.6,
          vote_count: 13719,
        },
        {
          adult: false,
          backdrop_path: '/kQGxGXzYiCumY8kmXXpgbZyZQK8.jpg',
          genre_ids: [80, 18, 9648, 53],
          id: 395834,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Wind River',
          overview:
            '보름달이 뜬 어느 날 밤, 발자국마저 사라지는 고요한 설원 위를 맨발로 달리던 한 소녀가 피를 토하며 죽는다. 안간힘을 쓰며 뛰어가던 그녀가 결국 피를 토하며 쓰러져 죽어 있는 모습을 사냥꾼 코리(제레미 레너)가 발견한다. 피해자는 그의 친구의 딸. 신입 FBI요원 제인(엘리자베스 올슨)이 사건 담당자로 그곳에 도착하지만 범인이 남긴 증거는 눈보라에 휩싸여 점점 사라지고, 수사는 난항을 겪는다. 3년 전, 윈드 리버에서 벌어진 살인 사건과의 유사점을 발견한 코리가 수사에 공조하면서  두 사람은 범인의 그림자에 빠른 속도로 접근하는데...',
          poster_path: '/lskBfr1zqKcgl6RYukNBt6pRWVj.jpg',
          release_date: '2017-08-03',
          title: '윈드 리버',
          video: false,
          vote_average: 7.4,
          vote_count: 3839,
        },
        {
          backdrop_path: '/gZzIQxo2ukFSdZGtlttA0wI6kax.jpg',
          first_air_date: '2011-06-05',
          genre_ids: [10765, 18],
          id: 34524,
          media_type: 'tv',
          name: '틴 울프',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Teen Wolf',
          overview:
            '어느 날 갑자기 늑대인간이 되어버린 후, 우정과 사랑을 지키며 스스로 살아남기 위해서 싸우는 고등학생 스캇의 이야기. 1985년 제작된 동명 영화를 리메이크한 작품.',
          poster_path: '/8Ij1O2nU8exLgwPXU8Eo6PZdCDC.jpg',
          vote_average: 8.6,
          vote_count: 2908,
        },
      ],
      known_for_department: 'Acting',
      name: 'Kelsey Asbille',
      popularity: 47.932,
      profile_path: '/8mXqxKaPc6FpAnLeZlPaaUaJHdC.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 1980651,
      known_for: [
        {
          adult: false,
          backdrop_path: '/ouOojiypBE6CD1aqcHPVq7cJf2R.jpg',
          genre_ids: [53],
          id: 578701,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Those Who Wish Me Dead',
          overview:
            '화재 현장에서 세 명의 아이를 구하지 못한 죄책감과 트라우마로 감시탑에 배정된 공수소방대원 한나는 거대 범죄의 증거를 가지고 도주 중인 소년을 만난다. 한편 소년을 쫓던 두 명의 킬러는 사람들의 눈을 돌리기 위해 불을 내고 삽시간에 번져가는데…  죽이려는 자와 지키려는 자, 거대한 불길 속에서 치닫는 생사를 건 대결. 그날 밤, 삶과 죽음이 타오르는 불길 속에 모두가 있었다!',
          poster_path: '/aMikd8jW6lZGmJgJ158biCjbNqZ.jpg',
          release_date: '2021-05-05',
          title: '내가 죽기를 바라는 자들',
          video: false,
          vote_average: 6.9,
          vote_count: 942,
        },
        {
          backdrop_path: '/5YTM1bh3Jyfy9IP2eS64W3JDeGs.jpg',
          first_air_date: '2018-06-20',
          genre_ids: [37, 18],
          id: 73586,
          media_type: 'tv',
          name: '옐로우스톤',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Yellowstone',
          overview:
            '미국 최초의 국립 공원과 국경을 접하는 사람들의 지속적인 공격을 받으면서 미국에서 가장 큰 목장을 관리하는 존 던트의 이야기',
          poster_path: '/43nVQqVsrshaOx9GfJq6JstsfCX.jpg',
          vote_average: 7.9,
          vote_count: 689,
        },
        {
          adult: false,
          backdrop_path: '/5UkzNSOK561c2QRy2Zr4AkADzLT.jpg',
          genre_ids: [878, 53],
          id: 528085,
          media_type: 'movie',
          original_language: 'en',
          original_title: '2067',
          overview:
            '지구 종말이 도래하고, 산소가 중요한 화폐가 된 서기 2067년. ‘타임머신’이라고 불리는 일명 ‘크로니컬’이 발명되고, 407년 뒤, 2474년 미래에서 보낸 메시지가 도착한다. 인류의 마지막 희망, 미래를 구해야만 한다',
          poster_path: '/7D430eqZj8y3oVkLFfsWXGRcpEG.jpg',
          release_date: '2020-10-01',
          title: '2067',
          video: false,
          vote_average: 5.1,
          vote_count: 547,
        },
      ],
      known_for_department: 'Acting',
      name: 'Finn Little',
      popularity: 44.897,
      profile_path: '/zWqSCCRvC2Bsb1T5t8JWqakVKmx.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 3041823,
      known_for: [
        {
          backdrop_path: '/3LhamTOykvDT64mJSbwjvNqT84T.jpg',
          first_air_date: '2020-03-06',
          genre_ids: [16],
          id: 100210,
          media_type: 'tv',
          name: 'お兄ちゃん, 朝までずっとギュッてして!',
          origin_country: ['JP'],
          original_language: 'ja',
          original_name: 'お兄ちゃん, 朝までずっとギュッてして!',
          overview: '',
          poster_path: '/fikdxPqIBSVXN5GWaUjXOxjQyl6.jpg',
          vote_average: 0,
          vote_count: 0,
        },
      ],
      known_for_department: 'Acting',
      name: 'Yotsuba Yō',
      popularity: 42.547,
      profile_path: null,
    },
    {
      adult: false,
      gender: 1,
      id: 2993250,
      known_for: [
        {
          adult: false,
          backdrop_path: '/ffmL3bKnqYtmqCwzzGraULN7tB4.jpg',
          genre_ids: [],
          id: 849780,
          media_type: 'movie',
          original_language: 'hi',
          original_title: 'Amar Prem',
          overview: '',
          poster_path: '/mYuRN5wNhycf4B2tDATygEuD14E.jpg',
          release_date: '2020-09-30',
          title: 'Amar Prem',
          video: false,
          vote_average: 0,
          vote_count: 0,
        },
        {
          adult: false,
          backdrop_path: '/uAn0pVaH2ODQqKqdBU4A2mplu7i.jpg',
          genre_ids: [],
          id: 849782,
          media_type: 'movie',
          original_language: 'hi',
          original_title: 'Khwaab',
          overview: '',
          poster_path: '/axvPIkEPhb6pm6OWK2rDdsOEl7G.jpg',
          release_date: '2020-10-12',
          title: 'Khwaab',
          video: false,
          vote_average: 0,
          vote_count: 0,
        },
        {
          adult: false,
          backdrop_path: '/lVuqbXjeuZuFlFQ7CUStDjWxVhz.jpg',
          genre_ids: [],
          id: 849783,
          media_type: 'movie',
          original_language: 'hi',
          original_title: 'Lonely Girl',
          overview: '',
          poster_path: '/qEjG9s3ELvsNO4RwhP0WCuuMGjs.jpg',
          release_date: '2020-08-09',
          title: 'Lonely Girl',
          video: false,
          vote_average: 0,
          vote_count: 0,
        },
      ],
      known_for_department: 'Acting',
      name: 'Jayati Thakar',
      popularity: 41.585,
      profile_path: '/3ZKhEmm1gz2rxhiWFe0xxhhylUj.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 62,
      known_for: [
        {
          adult: false,
          backdrop_path: '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
          genre_ids: [53, 80],
          id: 680,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Pulp Fiction',
          overview:
            '펌프킨와 허니 버니가 레스토랑에서 강도 행각을 벌이기 시작한다. 빈센트와 그 동료 쥴스는 두목의 금가방을 찾기 위해 다른 건달이 사는 아파트를 찾아간다. 마르셀러스는 부치에게 돈을 주며 상대 선수에게 져 주라고 하지만 부치는 상대 선수를 때려 눕히고 도망치다, 어릴 때 아버지에게 물려받은 시계를 찾기 위해 아파트로 향한다. 아무런 상관 없이 보이는 이 사건들이 서로 얽히고 섥히면서 예상치 못한 인과관계가 만들어지는데...',
          poster_path: '/6lXRHGoEbnnBUKsuqpL9JxD4DzT.jpg',
          release_date: '1994-09-10',
          title: '펄프 픽션',
          video: false,
          vote_average: 8.5,
          vote_count: 22207,
        },
        {
          adult: false,
          backdrop_path: '/9pkZesKMnblFfKxEhQx45YQ2kIe.jpg',
          genre_ids: [27, 53],
          id: 381288,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Split',
          overview:
            '23개의 인격을 가진 남자 케빈(제임스 맥어보이). 어릴 때 엄마에게 학대를 당한 그는 자신을 보호하기 위해 인격들의 리더인 배리, 미성숙한 9살 소년 헤드윅, 여성 패트리샤, 강박증이 있는 데니스 등 23개의 인격을 만들어냈다. 유일하게 자신을 이해하는 플레처 박사(베티 버클리)와 상담을 나누며 인격들을 컨트롤하던 그에게 어느 날 비스트라는 24번째 인격에 대한 믿음이 생겨난다. 비스트를 불러내고자 하는 인격들은 세명의 10대 소녀 케이시, 클레어, 마샤를 납치해 감금한다. 케이시는 과거 아버지와 사냥했던 경험과 삼촌에게 학대당했던 기억을 상기하며 탈출 방법을 찾아나간다.',
          poster_path: '/pF58P50otT55n4H1ELw1qtUrTcS.jpg',
          release_date: '2016-11-15',
          title: '23 아이덴티티',
          video: false,
          vote_average: 7.3,
          vote_count: 14477,
        },
        {
          adult: false,
          backdrop_path: '/6TjllWT3cGrPFyqDXurVZ3L8bBi.jpg',
          genre_ids: [9648, 53, 18],
          id: 745,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'The Sixth Sense',
          overview:
            "아동 심리학자인 크로우 박사(브루스 윌리스)는 필라델피아 주지사에게 아동을 위해 기여했다는 공로로 상을 받는다. 그날 밤, 부인과 함께 2층에 올라간 말콤 박사는 낯선 침입자를 발견하게 된다. 그 침입자는 몇 년 전 말콤 박사가 치료를 맡았던 '빈센트 그레이'라는 환자인데, 박사는 그에게 총상을 입고 그는 자살한다. 이듬 해 가을, 총상에서 회복한 크로우 박사는 '콜 시어'라는 자폐증에 걸린 8살 된 소년의 정신 치료를 맡게 된다. 콜은 처음엔 쉽게 마음을 열지 않다가 박사의 계속된 노력으로 누구에게도 말하지 않은 비밀을 말한다. 즉 콜은 항상 귀신들이 보이며, 귀신들은 자신이 죽었는지조차 모르고, 보고 싶은 것만 본다고 이야기한다. 박사는 쉽게 믿으려 하지를 않고 마침 부인의 외도를 목격한 후 콜의 치료를 포기하려고 한다. 그러다가 박사는 옛 환자였던 빈센트와의 상담 녹음 테잎에서 귀신의 소리인 듯한 소리를 듣게 되고 콜을 찾아가 콜이 귀신에 대한 공포를 이겨내는 걸 돕게 된다.",
          poster_path: '/74iA0M8TI2N0E1kQpcB6ZWocPO5.jpg',
          release_date: '1999-08-06',
          title: '식스 센스',
          video: false,
          vote_average: 7.9,
          vote_count: 9084,
        },
      ],
      known_for_department: 'Acting',
      name: 'Bruce Willis',
      popularity: 40.446,
      profile_path: '/caX3KtMU42EP3VLRFFBwqIIrch5.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 3896,
      known_for: [
        {
          adult: false,
          backdrop_path: '/cKPfiu9IcCW0fMdKdQBXe3PRtTZ.jpg',
          genre_ids: [28, 80, 18, 53],
          id: 49026,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'The Dark Knight Rises',
          overview:
            '배트맨이 조커와의 대결을 끝으로 세상에서 모습을 감춘 8년 후, 하비 덴트의 죽음에 대한 책임을 떠안은 배트맨은 모든 것을 희생하며 떠난다. 범죄방지 덴트법으로 인해 한동안 평화가 지속되던 고담시의 파멸을 예고하며 나타난 마스크를 쓴 잔인한 악당, 최강의 적 베인이 등장한다. 베인은 배트맨이 스스로 택한 유배 생활에 종지부를 찍게 하지만, 다시 돌아온 배트맨에게 베인은 만만한 상대가 아니다. 자신을 거부한 사람들의 고통을 지켜볼 것인가, 정의의 수호자로 나설 것인가. 배트맨은 승패를 알 수 없는 마지막 전투를 시작하려 하는데...',
          poster_path: '/stbZZs3WMPr9rvAT92Qd8gXCUfx.jpg',
          release_date: '2012-07-16',
          title: '다크 나이트 라이즈',
          video: false,
          vote_average: 7.8,
          vote_count: 18662,
        },
        {
          adult: false,
          backdrop_path: '/y9AuabF1SXnn3xZ0tAJLLhv33Uj.jpg',
          genre_ids: [28, 80, 18],
          id: 272,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Batman Begins',
          overview:
            '브루스 웨인은 어린 시절, 부모님이 길거리에서 피살되는 것을 눈 앞에서 지켜본 후 죄의식과 분노로 늘 고통 받는다. 복수의 욕망과 부모님의 가르침 사이에서 갈등하던 그는 악을 물리칠 방법을 터득하기 위해 고담시를 떠나 홀로 세상을 유랑하던 중 듀커드라는 수수께끼의 인물을 만나 가름침을 받고, 듀커드는 브루스에게 어둠의 사도들에 가입하라는 제안을 한다. 듀커드가 속해있는 어둠의 사도들은 라스 알 굴이 이끄는 범죄 소탕 조직. 그러나 브루스는 눈에는 눈, 이에는 이라는 강경책으로 응징하는 이들의 방법이 자신과는 맞지 않음을 깨닫고 고담시로 돌아온다.',
          poster_path: '/sb3V2fPhNDRRUvHJW4pQaeHbDxm.jpg',
          release_date: '2005-06-10',
          title: '배트맨 비긴즈',
          video: false,
          vote_average: 7.7,
          vote_count: 16910,
        },
        {
          adult: false,
          backdrop_path: '/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg',
          genre_ids: [18, 36, 10752],
          id: 424,
          media_type: 'movie',
          original_language: 'en',
          original_title: "Schindler's List",
          overview:
            '2차 세계대전 당시 독일군이 점령한 폴란드. 시류에 맞춰 자신의 성공을 추구하는 기회주의자 쉰들러는 유태인이 경영하는 그릇 공장을 인수한다. 그는 공장을 인수하기 위해 나찌 당원이 되고 독일군에게 뇌물을 바치는 등 갖은 방법을 동원한다. 그러나 냉혹한 기회주의자였던 쉰들러는 유태인 회계사인 스턴과 친분을 맺으면서 냉혹한 유태인 학살에 대한 양심의 소리를 듣기 시작한다. 마침내 그는 강제 수용소로 끌려가 죽음을 맞게될 유태인들을 구해내기로 결심하고, 독일군 장교에게 빼내는 사람 숫자대로 뇌물을 주는 방법으로 유태인들을 구해내려는 계획을 세우는데...',
          poster_path: '/oyyUcGwLX7LTFS1pQbLrQpyzIyt.jpg',
          release_date: '1993-11-30',
          title: '쉰들러 리스트',
          video: false,
          vote_average: 8.6,
          vote_count: 12102,
        },
      ],
      known_for_department: 'Acting',
      name: 'Liam Neeson',
      popularity: 39.69,
      profile_path: '/bboldwqSC6tdw2iL6631c98l2Mn.jpg',
    },
    {
      adult: false,
      gender: 1,
      id: 130640,
      known_for: [
        {
          adult: false,
          backdrop_path: '/6qVF0gnLnbKCgcMfCpCB8GH7B5I.jpg',
          genre_ids: [28, 12, 16, 878, 35],
          id: 324857,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Spider-Man: Into the Spider-Verse',
          overview:
            '평범한 10대 마일스 모랄레스는 우연히 방사능 거미에 물려 스파이더맨 능력을 가지게 된다. 혼란스러워하던 마일스는 악당과 싸우고 있는 피터 파커를 마주치게 되고 피터 파커는 마일스가 자신과 같은 능력을 가지고 있음을 직감한다. 여러 개의 평행세계가 존재한다는 것을 알게 된 마일스와 피터 파커는 이후 스파이더우먼 스파이더 그웬, 스파이더맨 누아르, 스파이더햄 등 평행세계 속 공존하는 모든 스파이더맨들을 만나게 되는데... 하나의 유니버스에서 만나 팀을 결성한 스파이더맨들은 과연 세계를 구할 수 있을까?',
          poster_path: '/vnWgIIEWAvWKOI65tm6h6VRbyY8.jpg',
          release_date: '2018-12-06',
          title: '스파이더맨: 뉴 유니버스',
          video: false,
          vote_average: 8.4,
          vote_count: 10291,
        },
        {
          adult: false,
          backdrop_path: '/qGqlWb5izTPtFngBWdbJAEmninR.jpg',
          genre_ids: [878, 28, 12],
          id: 80274,
          media_type: 'movie',
          original_language: 'en',
          original_title: "Ender's Game",
          overview:
            "외계 종족 ‘포믹’의 공격에서 가까스로 살아남은 뒤 우주함대를 결성한 인류는 지구를 지켜낼 단 한 명의 영웅으로 뛰어난 지능과 천재적 전략을 지닌 '엔더'를 선택한다. 외로움과 고통을 이겨내고 철저한 훈련과 시뮬레이션 전투를 통해 우주함대 최고의 지휘관으로 성장한 엔더. 외계의 2차 침공 가능성은 점점 커지고, 이제 그에게 남은 것은 인류의 미래가 걸린 최후의 반격! 이길 것인가? 지배당할 것인가! 지구의 운명을 건 최후의 반격이 시작된다!",
          poster_path: '/h5cTRuGr5ke9skfCPgNWAiXT78v.jpg',
          release_date: '2013-10-24',
          title: '엔더스 게임',
          video: false,
          vote_average: 6.6,
          vote_count: 4752,
        },
        {
          adult: false,
          backdrop_path: '/hMANgfPHR1tRObNp2oPiOi9mMlz.jpg',
          genre_ids: [28, 12, 878],
          id: 424783,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Bumblebee',
          overview:
            '지속된 디셉티콘과의 전쟁에서 위기에 몰린 옵티머스 프라임은 중요한 임무를 가진 오토봇을 지구로 보낸다.  지구에 도착한 오토봇은 인간들에게 쫓기게 되고, 낡은 비틀로 변신해 폐차장에 은둔하던 중,  찰리라는 소녀에 의해 발견된다.  비틀을 수리하던 찰리는 자신의 낡은 자동차가 거대한 로봇으로 변신하는 놀라운 광경을 목격하고,  모든 기억이 사라진 그에게 ‘범블비’라는 이름을 지어주며 서로에게 특별한 존재가 되어간다.  하지만, 범블비의 정체를 파헤치려는 인간들과 그가 가진 비밀을 쫓는 디셉티콘의 추격과 압박은 점점 더 심해지는데…',
          poster_path: '/a1XTVjEiShbX1XE6Uvaho49gw3l.jpg',
          release_date: '2018-12-15',
          title: '범블비',
          video: false,
          vote_average: 6.7,
          vote_count: 4695,
        },
      ],
      known_for_department: 'Acting',
      name: 'Hailee Steinfeld',
      popularity: 38.852,
      profile_path: '/dxSDWkiVaC6JYjrV3XRAZI7HOSS.jpg',
    },
    {
      adult: false,
      gender: 1,
      id: 1388593,
      known_for: [
        {
          adult: false,
          backdrop_path: '/SPkEiZGxq5aHWQ2Zw7AITwSEo2.jpg',
          genre_ids: [28, 12, 878],
          id: 181812,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Star Wars: The Rise of Skywalker',
          overview:
            '포스의 균형을 교란시키는 퍼스트 오더의 수장 카일로 렌의 횡포가 극에 달한다. 저항군의 수장 레아 장군은 스타킬러 기지 파괴에는 성공하나 저항군 세력의 상당수를 잃고 전략적 후퇴를 선택한다. 퍼스트 오더 군대 내에 스파이를 두어 동태를 살피던 포 다메론은 팰퍼틴이 생존해 군대를 꾸린다는 첩보를 접한다. 제다이 수련에 빠져 있던 레이, 능숙한 파일럿으로 거듭난 핀과 포를 비롯한 소수 정예의 저항군은 팰퍼틴이 숨어 있다고 알려진 다크 사이드의 본거지 엑시골의 위치를 알아내기 위한 비밀작전을 수행한다.',
          poster_path: '/cJevdcvbBw0FhpUtrwmj1MYMiK3.jpg',
          release_date: '2019-12-18',
          title: '스타워즈: 라이즈 오브 스카이워커',
          video: false,
          vote_average: 6.5,
          vote_count: 7279,
        },
        {
          adult: false,
          backdrop_path: '/8Y43POKjjKDGI9MH89NW0NAzzp8.jpg',
          genre_ids: [35, 28, 12, 878],
          id: 550988,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Free Guy',
          overview:
            '평범한 직장, 절친 그리고 한 잔의 커피.  평화로운 일상 속 때론 총격전과 날강도가 나타나는 버라이어티한 ‘프리시티’에 살고 있는 ‘가이’. 그에겐 뭐 하나 부족한 것이 없었다. 우연히 마주친 그녀에게 한눈에 반하기 전까지는…  갖은 노력 끝에 다시 만난 그녀는 ‘가이’가 비디오 게임 ‘프리시티’에 사는 배경 캐릭터이고, 이 세상은 곧 파괴될 거라 경고한다. 혼란에 빠진 ‘가이’ 그러나 그는 ‘프리시티’의 파괴를 막기 위해 더 이상 배경 캐릭터가 아닌, 히어로가 되기로 결심한다.',
          poster_path: '/sEYyQ4lW43jg77yTiTSRUNVdtMc.jpg',
          release_date: '2021-08-11',
          title: '프리 가이',
          video: false,
          vote_average: 7.8,
          vote_count: 4015,
        },
        {
          backdrop_path: '/scoyQvVpyrJIS29dIffRdKgMW9S.jpg',
          first_air_date: '2018-04-08',
          genre_ids: [80, 18],
          id: 72750,
          media_type: 'tv',
          name: '킬링 이브',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Killing Eve',
          overview:
            '일도 사랑도 권태에 빠진 여자가 사이코패스 킬러와 쫓고 쫓기는 추격전을 그린 드라마. 범죄 심리에 병적인 흥미를 가진 영국 정보국 요원 이브, 청부 살인에 희열을 느끼며 살아가는 사이코패스 킬러 빌라넬. 알 수 없는 집착에 사로잡혀 서로를 쫓기 시작한다.',
          poster_path: '/kQdFjDPiC8xfbDFEu3eo285wYIu.jpg',
          vote_average: 8.2,
          vote_count: 755,
        },
      ],
      known_for_department: 'Acting',
      name: 'Jodie Comer',
      popularity: 38.221,
      profile_path: '/va8pcuzXodVLYUQLjB1USZVB6gz.jpg',
    },
  ],
};
